# Generated by Django 5.2.3 on 2025-07-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('image', models.ImageField(upload_to='games_images')),
                ('genre', models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('rpg', 'RPG'), ('simulation', 'Simulation'), ('strategy', 'Strategy'), ('sports', 'Sports'), ('racing', 'Racing'), ('shooter', 'Shooter'), ('fighting', 'Fighting'), ('horror', 'Horror'), ('stealth', 'Stealth'), ('survival', 'Survival'), ('singleplayer', 'Singleplayer'), ('multiplayer', 'Multiplayer'), ('first_person', 'First Person'), ('third_person', 'Third Person'), ('co_op', 'Co-Op'), ('fps_tps', 'FPS/TPS')], max_length=50)),
                ('genre2', models.CharField(blank=True, choices=[('action', 'Action'), ('adventure', 'Adventure'), ('rpg', 'RPG'), ('simulation', 'Simulation'), ('strategy', 'Strategy'), ('sports', 'Sports'), ('racing', 'Racing'), ('shooter', 'Shooter'), ('fighting', 'Fighting'), ('horror', 'Horror'), ('stealth', 'Stealth'), ('survival', 'Survival'), ('singleplayer', 'Singleplayer'), ('multiplayer', 'Multiplayer'), ('first_person', 'First Person'), ('third_person', 'Third Person'), ('co_op', 'Co-Op'), ('fps_tps', 'FPS/TPS')], max_length=50, null=True, verbose_name='Secondary Genre')),
                ('genre3', models.CharField(blank=True, choices=[('action', 'Action'), ('adventure', 'Adventure'), ('rpg', 'RPG'), ('simulation', 'Simulation'), ('strategy', 'Strategy'), ('sports', 'Sports'), ('racing', 'Racing'), ('shooter', 'Shooter'), ('fighting', 'Fighting'), ('horror', 'Horror'), ('stealth', 'Stealth'), ('survival', 'Survival'), ('singleplayer', 'Singleplayer'), ('multiplayer', 'Multiplayer'), ('first_person', 'First Person'), ('third_person', 'Third Person'), ('co_op', 'Co-Op'), ('fps_tps', 'FPS/TPS')], max_length=50, null=True, verbose_name='third Genre')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('console', models.CharField(choices=[('Ps3', 'PlayStation3'), ('Ps4', 'PlayStation4'), ('Ps5', 'PlayStation5'), ('Xbox360', 'Xbox 360'), ('XboxOne', 'Xbox One'), ('XboxSeriesX', 'Xbox Series X'), ('Switch', 'Nintendo Switch'), ('PC', 'PC')], max_length=50)),
                ('trailer', models.URLField(blank=True, default='')),
                ('min_age', models.IntegerField(choices=[(0, 0), (6, 6), (12, 12), (16, 16), (18, 18)], default=0)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True)),
            ],
        ),
    ]
