# Generated by Django 5.2.3 on 2025-07-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image_url',
            field=models.URLField(blank=True, help_text='Or provide an image URL', null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image file', null=True, upload_to='games_images'),
        ),
    ]
