# Generated by Django 5.2.3 on 2025-07-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_image_url_alter_game_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
