# Generated by Django 5.2.3 on 2025-07-12 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_game_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='game',
            name='genre2',
        ),
        migrations.RemoveField(
            model_name='game',
            name='genre3',
        ),
        migrations.CreateModel(
            name='Game_Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('rpg', 'RPG'), ('simulation', 'Simulation'), ('strategy', 'Strategy'), ('sports', 'Sports'), ('racing', 'Racing'), ('shooter', 'Shooter'), ('fighting', 'Fighting'), ('horror', 'Horror'), ('stealth', 'Stealth'), ('survival', 'Survival'), ('singleplayer', 'Singleplayer'), ('multiplayer', 'Multiplayer'), ('first_person', 'First Person'), ('third_person', 'Third Person'), ('co_op', 'Co-Op'), ('fps_tps', 'FPS/TPS')], max_length=50)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_genres', to='game.game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='games', to='game.game_genre'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='game.game')),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('expiration_date', models.DateField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='game.game')),
            ],
        ),
    ]
