# Generated by Django 5.2.3 on 2025-07-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_game_genre_remove_game_genre2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='game_genre',
            name='game',
        ),
        migrations.AddField(
            model_name='game_genre',
            name='game',
            field=models.ManyToManyField(to='game.game'),
        ),
    ]
