# Generated by Django 5.2.3 on 2025-07-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_remove_game_genres_remove_game_genre_game_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game_genre',
            name='game',
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(to='game.game_genre'),
        ),
    ]
