# Generated by Django 5.2.3 on 2025-07-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_remove_game_genre_game_game_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_genre',
            name='games',
            field=models.ManyToManyField(to='game.game'),
        ),
    ]
