# Generated by Django 5.2.3 on 2025-07-13 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_game_genre_games'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game_genre',
            name='games',
        ),
    ]
