# Generated by Django 5.2.3 on 2025-07-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_remove_game_genre_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(related_name='GENRE_CHOICES', to='game.game_genre'),
        ),
    ]
