# Generated by Django 5.2.3 on 2025-07-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_game_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='min_cpu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='min_gpu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='min_ram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='min_storage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='recommended_cpu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='recommended_gpu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='recommended_ram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='recommended_storage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='console',
            field=models.CharField(choices=[('Ps3', 'PlayStation 3'), ('Ps4', 'PlayStation 4'), ('Ps5', 'PlayStation 5'), ('Xbox360', 'Xbox 360'), ('XboxOne', 'Xbox One'), ('XboxSeriesX', 'Xbox Series X/S'), ('Switch', 'Nintendo Switch'), ('PC', 'PC')], max_length=50),
        ),
    ]
