# Generated by Django 5.2.3 on 2025-07-13 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_game_min_cpu_game_min_gpu_game_min_ram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='min_cpu',
        ),
        migrations.RemoveField(
            model_name='game',
            name='min_gpu',
        ),
        migrations.RemoveField(
            model_name='game',
            name='min_ram',
        ),
        migrations.RemoveField(
            model_name='game',
            name='min_storage',
        ),
        migrations.RemoveField(
            model_name='game',
            name='recommended_cpu',
        ),
        migrations.RemoveField(
            model_name='game',
            name='recommended_gpu',
        ),
        migrations.RemoveField(
            model_name='game',
            name='recommended_ram',
        ),
        migrations.RemoveField(
            model_name='game',
            name='recommended_storage',
        ),
    ]
