# Generated by Django 5.2.3 on 2025-07-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_game_min_cpu_game_min_gpu_game_min_ram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='game',
        ),
        migrations.AlterField(
            model_name='game',
            name='min_cpu',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Minimum CPU'),
        ),
        migrations.AlterField(
            model_name='game',
            name='min_gpu',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Minimum GPU'),
        ),
        migrations.AlterField(
            model_name='game',
            name='min_ram',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Minimum RAM'),
        ),
        migrations.AlterField(
            model_name='game',
            name='min_storage',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Minimum Storage'),
        ),
        migrations.AlterField(
            model_name='game',
            name='rec_cpu',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Recommended CPU'),
        ),
        migrations.AlterField(
            model_name='game',
            name='rec_gpu',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Recommended GPU'),
        ),
        migrations.AlterField(
            model_name='game',
            name='rec_ram',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Recommended RAM'),
        ),
        migrations.AlterField(
            model_name='game',
            name='rec_storage',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Recommended Storage'),
        ),
        migrations.AlterField(
            model_name='game_genre',
            name='genre',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Voucher',
        ),
    ]
