# Generated by Django 5.2.3 on 2025-07-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_remove_voucher_game_alter_game_min_cpu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='discount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='min_cpu',
            field=models.CharField(blank=True, default='N/A', max_length=100, verbose_name='Minimum CPU'),
        ),
        migrations.AlterField(
            model_name='game',
            name='min_gpu',
            field=models.CharField(blank=True, default='N/A', max_length=100, verbose_name='Minimum GPU'),
        ),
        migrations.AlterField(
            model_name='game',
            name='min_ram',
            field=models.CharField(blank=True, default='N/A', max_length=20, verbose_name='Minimum RAM'),
        ),
        migrations.AlterField(
            model_name='game',
            name='min_storage',
            field=models.CharField(blank=True, default='N/A', max_length=20, verbose_name='Minimum Storage'),
        ),
        migrations.AlterField(
            model_name='game',
            name='rec_cpu',
            field=models.CharField(blank=True, default='N/A', max_length=100, verbose_name='Recommended CPU'),
        ),
        migrations.AlterField(
            model_name='game',
            name='rec_gpu',
            field=models.CharField(blank=True, default='N/A', max_length=100, verbose_name='Recommended GPU'),
        ),
        migrations.AlterField(
            model_name='game',
            name='rec_ram',
            field=models.CharField(blank=True, default='N/A', max_length=20, verbose_name='Recommended RAM'),
        ),
        migrations.AlterField(
            model_name='game',
            name='rec_storage',
            field=models.CharField(blank=True, default='N/A', max_length=20, verbose_name='Recommended Storage'),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
