# Generated by Django 5.2.3 on 2025-07-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_alter_game_discount_alter_game_min_cpu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3),
        ),
    ]
