# Generated by Django 5.2.3 on 2025-07-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_alter_game_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
