# Generated by Django 5.2.3 on 2025-07-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_alter_game_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='available_stock',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
