# Generated by Django 5.2.3 on 2025-07-20 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_game_available_stock_game_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='available_stock',
        ),
        migrations.RemoveField(
            model_name='game',
            name='quantity',
        ),
    ]
