# Generated by Django 5.2.3 on 2025-07-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='created_at',
        ),
        migrations.AddField(
            model_name='cart',
            name='games',
            field=models.ManyToManyField(to='game.game'),
        ),
    ]
