# Generated by Django 5.2.3 on 2025-07-27 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_cartitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='game_price',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
