# Generated by Django 5.2.3 on 2025-08-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_alter_cartitem_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
