# Generated by Django 5.2.3 on 2025-08-02 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
