# Generated by Django 5.2.3 on 2025-08-03 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_delete_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='game_price',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
    ]
