# Generated by Django 5.2.3 on 2025-08-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0031_remove_cartitem_voucher_price_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='voucher_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
