# Generated by Django 5.2.3 on 2025-08-03 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0032_cartitem_voucher_price_delete_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='voucher_price',
            new_name='voucher_discount',
        ),
    ]
