# Generated by Django 5.2.1 on 2025-08-03 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0033_rename_voucher_price_cartitem_voucher_discount'),
        ('users_auth_app', '0032_alter_voucher_usage_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='voucher_used',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users_auth_app.voucher'),
        ),
    ]
