# Generated by Django 5.2.1 on 2025-08-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0034_cartitem_voucher_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='console',
            field=models.CharField(choices=[('PS4', 'PlayStation 4'), ('PS5', 'PlayStation 5'), ('Xbox One', 'Xbox One'), ('Xbox Series X/S', 'Xbox Series X/S'), ('Nintendo Switch', 'Nintendo Switch'), ('PC', 'PC')], max_length=50),
        ),
    ]
