# Generated by Django 5.2.1 on 2025-08-05 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0036_milesstones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milesstones',
            name='user',
        ),
    ]
