# Generated by Django 5.2.1 on 2025-07-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_alter_game_discount_alter_game_min_cpu_and_more'),
        ('users_auth_app', '0002_remove_customuser_name_alter_customuser_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_saved_games',
            field=models.ManyToManyField(blank=True, to='game.game'),
        ),
    ]
