# Generated by Django 5.2.3 on 2025-07-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_alter_game_discount'),
        ('users_auth_app', '0003_customuser_user_saved_games_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='game',
        ),
        migrations.AddField(
            model_name='order',
            name='game',
            field=models.ManyToManyField(to='game.game'),
        ),
    ]
