# Generated by Django 5.2.1 on 2025-07-25 19:02

import users_auth_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_app', '0007_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='gift_code',
            field=models.CharField(default=users_auth_app.models.Voucher.generate_voucher_code, max_length=10, unique=True),
        ),
    ]
