# Generated by Django 5.2.1 on 2025-07-25 19:06

import users_auth_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_app', '0008_alter_voucher_gift_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='gift_code',
            field=models.CharField(blank=True, default=users_auth_app.models.Voucher.generate_voucher_code, max_length=10, null=True, unique=True),
        ),
    ]
