# Generated by Django 5.2.1 on 2025-07-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_cartitem_delete_cart'),
        ('users_auth_app', '0009_alter_voucher_gift_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='games',
            field=models.ManyToManyField(to='game.game'),
        ),
    ]
