# Generated by Django 5.2.1 on 2025-07-25 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_app', '0010_alter_voucher_games'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucher',
            old_name='discount_percentage',
            new_name='discount',
        ),
    ]
