# Generated by Django 5.2.3 on 2025-07-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_cartitem_price'),
        ('users_auth_app', '0012_remove_voucher_gift_code_alter_voucher_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='game',
            field=models.ManyToManyField(to='game.cartitem'),
        ),
    ]
