# Generated by Django 5.2.3 on 2025-07-27 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_alter_cartitem_price'),
        ('users_auth_app', '0017_alter_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='game_title',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.game'),
        ),
    ]
