# Generated by Django 5.2.3 on 2025-07-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_app', '0019_gamelibrary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamelibrary',
            name='quandity',
        ),
        migrations.AddField(
            model_name='gamelibrary',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
