# Generated by Django 5.2.3 on 2025-07-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_app', '0020_remove_gamelibrary_quandity_gamelibrary_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_library_synced',
            field=models.BooleanField(default=False),
        ),
    ]
