# Generated by Django 5.2.3 on 2025-07-31 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_app', '0021_order_is_library_synced'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelibrary',
            name='totalgames',
            field=models.IntegerField(null=True),
        ),
    ]
