# Generated by Django 5.2.3 on 2025-07-31 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_app', '0022_gamelibrary_totalgames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamelibrary',
            name='totalgames',
        ),
    ]
