# Generated by Django 5.2.3 on 2025-07-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_app', '0023_remove_gamelibrary_totalgames'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelibrary',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
