# Generated by Django 5.2.1 on 2025-08-03 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_app', '0024_gamelibrary_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamelibrary',
            name='count',
        ),
        migrations.AddField(
            model_name='gamelibrary',
            name='order_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users_auth_app.orderitem'),
        ),
    ]
