# Generated by Django 5.2.1 on 2025-08-03 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_app', '0025_remove_gamelibrary_count_gamelibrary_order_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gamelibrary',
        ),
    ]
