# Generated by Django 5.2.1 on 2025-08-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_app', '0026_delete_gamelibrary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_saved_games',
        ),
        migrations.AddField(
            model_name='customuser',
            name='games_ordered',
            field=models.IntegerField(null=True),
        ),
    ]
