# Generated by Django 5.2.1 on 2025-08-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_app', '0027_remove_customuser_user_saved_games_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='games_ordered',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
