# Generated by Django 5.2.1 on 2025-08-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_app', '0028_alter_customuser_games_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='expiration_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='usage_limit',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
