# Generated by Django 5.2.1 on 2025-08-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_app', '0029_alter_voucher_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
