# Generated by Django 5.2.1 on 2025-08-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_app', '0035_alter_voucher_usage_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='usage_limit',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
