# Generated by Django 5.2.1 on 2025-08-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_app', '0038_alter_voucher_expiration_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='apartment',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
