# Generated by Django 5.2.1 on 2025-08-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_app', '0039_customuser_apartment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_library_synced',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='coupon_used',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
