# Generated by Django 5.2.1 on 2025-08-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_app', '0040_remove_order_is_library_synced_orderitem_coupon_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='milestone',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
