# Generated by Django 5.2.1 on 2025-08-04 20:58

import users_auth_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_app', '0041_voucher_milestone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='code',
            field=models.CharField(default=users_auth_app.models.Voucher.generate_voucher_code, max_length=8, unique=True),
        ),
    ]
