# Generated by Django 5.2.1 on 2025-08-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_auth_app', '0042_alter_voucher_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='apartment',
            field=models.CharField(blank=True, default='0', max_length=5),
        ),
    ]
